### ISSUE TITLE
Question - Pico to function as real USB MIDI device

### ISSUE THREAD

**Issue by hanshafner** [ashstrahle/Pi-Pico-ExpressionPedal2Midi#3]
If I understand correctly, the code will not send MIDI over USB to computer but to an actual hardware MIDI port.

Is it possible for you to estimate how difficult it would be to get this device to be a real MIDI device and function by simply plugging it into USB?

I'm trying to gauge if this would be something to look into but I'm a composer foremost and coding is only something I do on the side, so I'm limited in my capability...

EDIT: I just found this:
https://blog.4dcu.be/diy/2021/05/20/MIDIpad.html

and it looks like just importing these two libraries will turn a Pico into an actual MIDI device:
import usb_midi
import adafruit_midi

Hmm... maybe I will risk the jump...

Kind regards
Hans

**Comment by ashstrahle** [comment]
Hi @hanshafner. 

Thanks for your interest. At the time this project was written, there were no libraries available that present the Pico as a midi device in USB Host mode. The adafruit_midi library appears to provide this functionality, however would obviously require compatibility testing and extra dev. 

By all means, try importing those libraries, initialising the device and add a midi.send command to the main loop.

**Comment by ashstrahle** [comment]
Hi @hanshafner.

Ask and you shall receive! I've rewritten this project to CircuitPython and leveraged adafruit_midi.  It's now USB capable and sending midi messages simultaneously to USB and midi port. Please test and let me know how you go.

Enjoy!

Ashley

**Comment by hanshafner** [comment]
Wow... thank you!

I just ordered a Pico and will order the Pedal and then get to trying this... luckily if the MIDI goes out over USB I don't have to deal with the resistors and building it may be within my capabilities...

I'll report.

**Comment by ashstrahle** [comment]
Hi @hanshafner. Have you had a chance to test? USB functionality has been tested ok, however would like to know how you got on.

Cheers,

Ashley
